name: Build & deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install deps
        run: npm install

      - name: build
        run: npm run deploy

      - name: build
        run: |
          git config --global user.email ${{ secrets.GITHUB_MAIL }}
          git config --global user.name ${{ secrets.GITHUB_USER }}
          git remote set-url origin https://${{ secrets.GITHUB_PAGES_TOKEN }}@github.com/${{ secrets.GITHUB_USER }}/${{ secrets.GITHUB_REPO }}.git
          npm run deploy

